# - name: Configure ETCD servers
#   hosts: etcd
#   become: true
#   roles:
#     - install_etcd

- name: Configure PostgreSQL servers
  hosts: postgres
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - install_postgres
    - postgres_replication
    - prometheus.prometheus.postgres_exporter
    # - install_patroni
