- name: Include a play configure_db_servers
  ansible.builtin.import_playbook: configure_db_servers.yml

- name: Include a play configure_backend
  ansible.builtin.import_playbook: configure_backend.yml

- name: Include a play configure_frontend
  ansible.builtin.import_playbook: configure_frontend.yml

- name: Include a play configure_monitoring
  ansible.builtin.import_playbook: configure_monitoring.yml

- name: Include a play configure_firewall
  ansible.builtin.import_playbook: configure_firewall.yml

- name: Include a play configure_backup
  ansible.builtin.import_playbook: configure_backup.yml