---
# defaults file for install_patroni
patroni_scope: 'pg-ha-cluster'
patroni_config_dir: "/etc/patroni/"
patroni_replicator_password: 'Otus123'
patroni_postgres_password: 'Otus123'
pgtun_postgresql_setting: ''

postgresql_version: 14
postgresql_cluster: "main"
postgresql_base_conf_dir: "/etc/postgresql"
postgresql_config_location: "{{ postgresql_base_conf_dir }}/{{ postgresql_version }}/{{ postgresql_cluster}}"

postgresql_base_data_dir: "/var/lib/postgresql"
postgresql_data_path: "{{ postgresql_base_data_dir }}/{{ postgresql_version }}/{{ postgresql_cluster }}"



# pgtun
mem_size: "{{ ((ansible_memory_mb.real.total) / 1024) | round (0,'ceil') | int}}"
#pgtun_body: '{"dbVersion": "{{ postgresql_version }}","osType": "Linux","dbApplication": "WEB", "ram" : { "memory" : "{{ mem_size }}", "unit" : "GB"},"dataStorage": "SSD"}'

pgtun_body: '{"dbVersion": "V13","cores" : {{ ansible_processor_cores }}, "osType": "Linux", "dbApplication": "WEB", "ram": { "memory" : {{ mem_size }}, "unit" : "GB"}, "dataStorage": "SSD"}'

keepalived_password: 'hr0wg1chww8'
keepalived_ip: '192.168.57.100'