# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :buid => {
        :box_name => "centos/8",
        :ip_addr => '192.168.56.10',
        :box_version => "2011.0",
        :cpus => 2,
        :memory => 2048,
        :provision => "test.sh"
  }
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.box_version =boxconfig[:box_version]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.memory = boxconfig[:memory]
                vb.cpus = boxconfig[:cpus]
            end
            box.vm.provision "file", source: "./nginx.spec", destination: "/tmp/nginx.spec"
            box.vm.provision "shell", path: boxconfig[:provision]

        end
    end
end
