---
# handlers file for deploy_app

- name: Restart gunicorn
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: gunicorn

- name: Reload postgresql
  ansible.builtin.service:
    name: postgresql
    state: reloaded


- name: Reload patroni
  systemd:
    name: patroni
    state: reloaded
  delegate_to: "{{ leder_hostname }}"
