# code: language=ansible

- name: Haproxy | install components | apt
  ansible.builtin.package:
    name:
      - haproxy
    state: present
    update_cache: true
  tags: [install, haproxy]

- name: Haproxy | Set up config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg 
    mode: '0644'
  notify: Restart haproxy
  tags: haproxy

- name: Haproxy | Start service | systemd
  ansible.builtin.systemd_service:
    name: haproxy
    state: started
    enabled: true
  tags: haproxy