Script started on Mon 29 Jan 2024 12:43:29 PM UTC
]0;root@lvm:~[?1034h[root@lvm ~]# lvremove /dev/vg_root/lv_root
File descriptor 3 (/root/03.tm) leaked on lvremove invocation. Parent PID 1371: bash
Do you really want to remove active logical volume vg_root/lv_root? [y/n]: y
  Logical volume "lv_root" successfully removed
]0;root@lvm:~[root@lvm ~]# vgremove /dev/vg_root
File descriptor 3 (/root/03.tm) leaked on vgremove invocation. Parent PID 1371: bash
  Volume group "vg_root" successfully removed
]0;root@lvm:~[root@lvm ~]# pvremove /dev/sdb
File descriptor 3 (/root/03.tm) leaked on pvremove invocation. Parent PID 1371: bash
  Labels on physical volume "/dev/sdb" successfully wiped.
]0;root@lvm:~[root@lvm ~]# lvcreate -n LogVol_Home -L 2G /dev/VolGroup00
File descriptor 3 (/root/03.tm) leaked on lvcreate invocation. Parent PID 1371: bash
  Logical volume "LogVol_Home" created.
]0;root@lvm:~[root@lvm ~]# mkfs.xfs /dev/VolGroup00/LogVol_Home
meta-data=/dev/VolGroup00/LogVol_Home isize=512    agcount=4, agsize=131072 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=0, sparse=0
data     =                       bsize=4096   blocks=524288, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
]0;root@lvm:~[root@lvm ~]# mount /dev/VolGroup00/LogVol_Home /mnt/
]0;root@lvm:~[root@lvm ~]# cp -aR /home/* /mnt/
]0;root@lvm:~[root@lvm ~]# rm -rf /home/*
]0;root@lvm:~[root@lvm ~]# umount /mnt
]0;root@lvm:~[root@lvm ~]# mount /dev/VolGroup00/LogVol_Home /home/
]0;root@lvm:~[root@lvm ~]# echo "`blkid | grep Home | awk '{print $2}'` /home xfs defaults 0 0" >> /etc/fstab
]0;root@lvm:~[root@lvm ~]# touch /home/file{1..20}
]0;root@lvm:~[root@lvm ~]# ls /home/
file1  file10  file11  file12  file13  file14  file15  file16  file17  file18  file19  file2  file20  file3  file4  file5  file6  file7  file8  file9  [0m[38;5;27mvagrant[0m
]0;root@lvm:~[root@lvm ~]# lvcreate -L 100MB -s -n home_snap /dev/VolGroup00/LogVol_Home
File descriptor 3 (/root/03.tm) leaked on lvcreate invocation. Parent PID 1371: bash
  Rounding up size to full physical extent 128.00 MiB
  Logical volume "home_snap" created.
]0;root@lvm:~[root@lvm ~]# rm -f /home/file{11..20}
]0;root@lvm:~[root@lvm ~]# rm -f /home/file{11..20}[C[C[C[C[C[C[C[C[C[C[C[C[C[Clvcreate -L 100MB -s -n home_snap /dev/VolGroup00/LogVol_Home[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cs /home/[K
file1  file10  file2  file3  file4  file5  file6  file7  file8  file9  [0m[38;5;27mvagrant[0m
]0;root@lvm:~[root@lvm ~]# umount /home
]0;root@lvm:~[root@lvm ~]# lvconvert --merge /dev/VolGroup00/home_snap
File descriptor 3 (/root/03.tm) leaked on lvconvert invocation. Parent PID 1371: bash
  Merging of volume VolGroup00/home_snap started.
  VolGroup00/LogVol_Home: Merged: 100.00%
]0;root@lvm:~[root@lvm ~]# mount /home
]0;root@lvm:~[root@lvm ~]# mount /homelvconvert --merge /dev/VolGroup00/home_snap[C[C[C[C[C[C[C[C[C[C[C[C[C[Cumount /home[K[3Pls /home/
file1  file10  file11  file12  file13  file14  file15  file16  file17  file18  file19  file2  file20  file3  file4  file5  file6  file7  file8  file9  [0m[38;5;27mvagrant[0m
]0;root@lvm:~[root@lvm ~]# ls blk[K[K[K[Kblk
NAME                       MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                          8:0    0   40G  0 disk 
├─sda1                       8:1    0    1M  0 part 
├─sda2                       8:2    0    1G  0 part /boot
└─sda3                       8:3    0   39G  0 part 
  ├─VolGroup00-LogVol00    253:0    0    8G  0 lvm  /
  ├─VolGroup00-LogVol01    253:1    0  1.5G  0 lvm  [SWAP]
  └─VolGroup00-LogVol_Home 253:5    0    2G  0 lvm  /home
sdb                          8:16   0   10G  0 disk 
sdc                          8:32   0    2G  0 disk 
├─vg_var-lv_var_rmeta_0    253:2    0    4M  0 lvm  
│ └─vg_var-lv_var          253:7    0  952M  0 lvm  /var
└─vg_var-lv_var_rimage_0   253:3    0  952M  0 lvm  
  └─vg_var-lv_var          253:7    0  952M  0 lvm  /var
sdd                          8:48   0    1G  0 disk 
├─vg_var-lv_var_rmeta_1    253:4    0    4M  0 lvm  
│ └─vg_var-lv_var          253:7    0  952M  0 lvm  /var
└─vg_var-lv_var_rimage_1   253:6    0  952M  0 lvm  
  └─vg_var-lv_var          253:7    0  952M  0 lvm  /var
sde                          8:64   0    1G  0 disk 
]0;root@lvm:~[root@lvm ~]# df -[K[K[K[Kexit
exit

Script done on Mon 29 Jan 2024 12:46:07 PM UTC
