# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
    :box_name => "ubuntu/jammy64",
    :ip_addr => '192.168.56.101',
    :disks => {
      :sata1 => {
        :dfile => './sata1.vdi',
        :size => 250,
        :port => 2
      },
      :sata2 => {
        :dfile => './sata2.vdi',
        :size => 250, 
        :port => 3
      },
      :sata3 => {
        :dfile => './sata3.vdi',
        :size => 250,
        :port => 4
      },
      :sata4 => {
        :dfile => './sata4.vdi',
        :size => 250, 
        :port => 5
      }
    }
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        needsController = false
        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController =  true
          end
        end
        if needsController == true
          #vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          boxconfig[:disks].each do |dname, dconf|
            vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
          end
        end
      end
      box.vm.provision "shell", inline: <<-SHELL
        sudo apt update && sudo apt install -y mdadm smartmontools hdparm gdisk
        sudo mdadm --zero-superblock --force /dev/sd{c,d,e,f}
        sudo mdadm --create --verbose --force /dev/md127 -l10 -n 4 /dev/sd{c,d,e,f}
        sudo  echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
        sudo mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
        sudo parted -s /dev/md127 mklabel gpt
        sudo parted /dev/md127 mkpart primary ext4 0% 20%
        sudo parted /dev/md127 mkpart primary ext4 20% 40%
        sudo parted /dev/md127 mkpart primary ext4 40% 60%
        sudo parted /dev/md127 mkpart primary ext4 60% 80%
        sudo parted /dev/md127 mkpart primary ext4 80% 100%
        for i in $(seq 1 5); do sudo mkfs.ext4 /dev/md127p$i; done
        sudo mkdir -p /raid/part{1,2,3,4,5}
        for i in $(seq 1 5); do echo `sudo blkid /dev/md127p$i | cut -d ' ' -f2` /raid/part$i ext4 defaults 0 0 >> /etc/fstab; done
        sudo mount -a
        SHELL

    end
  end
end
