---
# handlers file for install_prometheus

- name: Restart Prometheus
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted


- name: Restart alertmanager
  ansible.builtin.systemd_service:
    name: alertmanager
    state: restarted
