---
# defaults file for install_postgrs

postgresql_version: 14
postgresql_cluster: "main"
postgresql_base_conf_dir: "/etc/postgresql"
postgresql_config_location: "{{ postgresql_base_conf_dir }}/{{ postgresql_version }}/{{ postgresql_cluster}}"

postgresql_base_data_dir: "/var/lib/postgresql"
postgresql_data_path: "{{ postgresql_base_data_dir }}/{{ postgresql_version }}/{{ postgresql_cluster }}"
# APT settings
postgresql_apt_key_id: "ACCC4CF8"
postgresql_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgresql_apt_repository: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main {{ postgresql_version }}"


# DNF (RedHat, Rocky, etc.)
postgresql_dnf_repository_baseurl: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm"
postgresql_pgdg_repository_url: "https://download.postgresql.org/pub/repos/yum/keys"
postgresql_rpm_repository_gpgkey: "{{ postgresql_pgdg_repository_url }}/PGDG-RPM-GPG-KEY-RHEL"

# pgtun
mem_size: "{{ ((ansible_memory_mb.real.total) / 1024) | round (0,'ceil') | int}}"
#pgtun_body: '{"dbVersion": "{{ postgresql_version }}","osType": "Linux","dbApplication": "WEB", "ram" : { "memory" : "{{ mem_size }}", "unit" : "GB"},"dataStorage": "SSD"}'

pgtun_body: '{"dbVersion": "V13","cores" : {{ ansible_processor_cores }}, "osType": "Linux", "dbApplication": "WEB", "ram": { "memory" : {{ mem_size }}, "unit" : "GB"}, "dataStorage": "SSD"}'