# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
    :lab09 => {
        :box_name => "centos/8",
        :box_version => "2011.0",
        :ip_addr => '192.168.56.101',
        :cpus => 2,
        :memory => 2048
    }
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box_version = boxconfig[:box_version]
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.memory = boxconfig[:memory]
                vb.cpus = boxconfig[:cpus]
                vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
            end
            #box.vm.provision "shell", path: boxconfig[:provision]
        end
    end
end
