# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :zfs => {
    :box_name => "ubuntu/jammy64",
    :box_version => "20240131.0.0",
    :ip_addr => '192.168.56.10',
    :provision => "test.sh",
    :disks => {
      :sata1 => {
        :dfile => './sata1.vdi',
        :size => 512,
        :port => 1
      },
      :sata2 => {
        :dfile => './sata2.vdi',
        :size => 512, # Megabytes
        :port => 2
      },
      :sata3 => {
        :dfile => './sata3.vdi',
        :size => 512,
        :port => 3
      },
      :sata4 => {
        :dfile => './sata4.vdi',
        :size => 512,
        :port => 4
      },
      :sata5 => {
        :dfile => './sata5.vdi',
        :size => 512,
        :port => 5
      },
      :sata6 => {
        :dfile => './sata6.vdi',
        :size => 512,
        :port => 6
      },
      :sata7 => {
        :dfile => './sata7.vdi',
        :size => 512,
        :port => 7
      },
      :sata8 => {
        :dfile => './sata8.vdi',
        :size => 512,
        :port => 8
      },
    }
  },
}
Vagrant.configure("2") do |config|
  config.vagrant.plugins = 'vagrant-host-shell'
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name =  boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        needsController = false
        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController =  true
          end
        end
        if needsController == true
          vb.customize ["storagectl", :id, "--name", "SAS", "--add", "sas", "--bootable=off"]
          boxconfig[:disks].each do |dname, dconf|
            vb.customize ['storageattach', :id,  '--storagectl', 'SAS', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
          end
        end
      end
      box.vm.provision "shell", path: boxconfig[:provision]
      box.vm.provision "host_shell" , inline: 'scp -i .vagrant/machines/zfs/virtualbox/private_key -P 2222 -o "StrictHostKeyChecking no" vagrant@127.0.0.1:/tmp/HW.log ./'
    end
  end
end
