# -*- mode: ruby -*-
# vi: set ft=ruby : vsa
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20240131.0.0"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end
  config.vm.define "nfss" do |nfss|
    nfss.vm.network "private_network", ip: "192.168.50.10",  virtualbox__intnet: "net1"
    nfss.vm.hostname = "nfss"
  end
  config.vm.define "nfsc" do |nfsc|
    nfsc.vm.network "private_network", ip: "192.168.50.11",  virtualbox__intnet: "net1"
    nfsc.vm.hostname = "nfsc"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-srv.yml"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-client.yml"
  end
end

