# code: language=ansible
- name: Prometheus | Ensure group exists "{{ prometheus_user }}"
  ansible.builtin.group:
    name: "{{ prometheus_user }}"
    system: true
    state: present
  tags: [monitoring, prometheus, install]

- name: Prometheus | Add the user '{{ prometheus_user }}'
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    shell: /sbin/nologin
    system: true
    groups: "{{ prometheus_user }}"
    append: true
  tags: [monitoring, prometheus, install]

- name: Prometheus | Create dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  loop:
    - "{{ prometheus_conf_dir }}"
    - "{{ prometheus_lib_dir }}"
  tags: [monitoring, prometheus, install]

- name: Prometheus | download prometheus distib | get_url
  ansible.builtin.get_url:
    url: "{{ prometheus_url }}"
    dest: "{{ tmp_dir }}/{{ prometheus_distr_arch }}"
    mode: '0640'
  tags: [monitoring, prometheus, install]

- name: Prometheus | Extract "{{ prometheus_distr_arch }}"
  ansible.builtin.unarchive:
    src: "{{ tmp_dir }}/{{ prometheus_distr_arch }}"
    dest: "{{ tmp_dir }}/"
    remote_src: true
  tags: [monitoring, prometheus, install]

- name: Prometheus | Copy bin file with owner and permissions
  ansible.builtin.copy:
    src: "{{ prometheus_install_tmp_dir }}/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0750'
    remote_src: true
  loop:
    - prometheus
    - promtool
  notify: Restart Prometheus
  tags: [monitoring, prometheus, install]

- name: Prometheus | Copy config file with owner and permissions | config
  ansible.builtin.copy:
    src: "{{ prometheus_install_tmp_dir }}/{{ item }}"
    dest: "{{ prometheus_conf_dir }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0644'
    directory_mode: '0755'
    remote_src: true
  loop:
    - consoles
    - console_libraries
  notify: Restart Prometheus
  tags: [monitoring, prometheus, install]

- name: Prometheus | Configure prometheus exporter
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_conf_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0640'
  notify: Restart Prometheus
  tags: [monitoring, prometheus]

- name: Prometheus | Configure service | systemctl
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/prometheus.service"
    owner: root
    group: root
    mode: '0640'
  notify: Restart Prometheus
  tags: [monitoring, prometheus, install]

- name: Prometheus | Start Prometheus
  ansible.builtin.systemd_service:
    name: prometheus
    state: started
    enabled: true
    masked: false
  tags: [monitoring, prometheus]
