---
# vars file for frontend
app_ips  : "{% set IP_ARR=[] %}{% for host in groups['app'] %}{% if IP_ARR.insert(loop.index,hostvars[host]['ansible_host']) %}{% endif %}{% endfor %}{{IP_ARR}}"
net: "{{ '^' + (listen_ip | split('.'))[0:3] | join('\\.') + '\\..*$' }}"
local_int: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4.address', 'match', net) | map(attribute='device') | first }}"


nat_net: "{{ '^' + (listen_ip | split('.'))[0:3] | join('\\.') + '\\..*$' }}"
nat_int: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4.address', 'match', nat_net) | map(attribute='device') | first }}"
