---
# defaults file for install_barman
master_user: 'postgres'
barman_user: 'barman'
barman_user_password: 'Otus2022!'
postgresql_version: 14
postgresql_cluster: "main"
postgresql_timezone: "UTC+3"
postgresql_db_name: "test"
postgresql_base_conf_dir: "/etc/postgresql"
postgresql_config_location: "{{ postgresql_base_conf_dir }}/{{ postgresql_version }}/{{ postgresql_cluster }}"
postgresql_base_data_dir: "/var/lib/postgresql"
postgresql_data_path: "{{  postgresql_base_data_dir }}/{{ postgresql_version }}/{{ postgresql_cluster }}"
postgresql_trigger_file: "/tmp/promotedb"
keepalived_ip: '192.168.57.100'
use_patroni: true
postgres_port: 5432
patroni_postgres_password: 'Otus123'
postgresql_cluster_port: 5000
postgresql_cluster_passive_port: 5001
