# code: language=ansible
---
- block:
  - name: PostgreSQL | Install all the required dependencies | apt
    ansible.builtin.apt:
      pkg: 
      - ca-certificates
      - python3-pexpect
      - python3-psycopg2
      - acl
      state: present
      update_cache: true

  - name: PostgreSQL | Add PostgreSQL repository apt-key | apt
    ansible.builtin.apt_key:
      id: "{{ postgresql_apt_key_id }}"
      url: "{{ postgresql_apt_key_url }}"
      state: present
      
  - name: PostgreSQL | Add PostgreSQL repository | apt
    ansible.builtin.apt_repository:
      repo: "{{ postgresql_apt_repository }}"
      state: present

  - name: PostgreSQL | Install PostgreSQL | apt
    apt:
      name:
        - "postgresql-{{postgresql_version}}"
        - "postgresql-client-{{postgresql_version}}"
        - "postgresql-contrib-{{postgresql_version}}"
      state: present
      update_cache: true

  - name: enable and start service
    ansible.builtin.service:
      name: postgresql
      state: started
      enabled: true

    