---
# handlers file for install_patroni
- name: Restart patroni
  ansible.builtin.systemd_service:
    name: patroni
    state: restarted

- name: Restart haproxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted

- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted


- name: Reboot machine
  ansible.builtin.reboot:
