---
# handlers file for frontend
- name: Restart Angie
  ansible.builtin.systemd_service:
    state: restarted
    name: angie

- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
