# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
    :lab10 => {
        :box_name => "centos/8",
        :box_version => "2011.0",
        :ip_addr => '192.168.56.101',
        :cpus => 2,
        :memory => 2048
    }
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box_version = boxconfig[:box_version]
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.memory = boxconfig[:memory]
                vb.cpus = boxconfig[:cpus]
                vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
            end
            config.vm.provision "file", source: "log_analizer.sh", destination: "/tmp/log_analizer.sh"
            config.vm.provision "file", source: "cron", destination: "/tmp/log_analizer"
            box.vm.provision "shell" , privileged: true, inline:<<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                mv /tmp/log_analizer.sh /usr/bin/
                mv /tmp/log_analizer /etc/cron.d
                chmod +x /usr/bin/log_analizer.sh
                cd /etc/yum.repos.d/
                sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
                sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
                yum install -y nginx
                systemctl enable nginx
                systemctl restart nginx
            SHELL
        end
    end
end
