---
# tasks file for install-etcd


- name: Include tasks "check_cluster_status"
  ansible.builtin.include_tasks:
    file: 'check_cluster_status.yml'

- name: Etcd | install components | apt
  ansible.builtin.package:
    name:
      - etcd
    state: present
    update_cache: true
  tags: etcd


- name: Set up etcd config
  ansible.builtin.template:
    src: etcd.j2
    dest: /etc/default/etcd
    mode: '0644'
  notify: Restart etcd
  tags: etcd
    

- name: Include tasks "new_cluster"
  ansible.builtin.include_tasks:
    file: 'new_cluster.yml'
  # when: 'quorum_status  | float > half_hosts | float'
  when: 'quorum_status | int <= 1'


- name: Include tasks "repalce_node"
  ansible.builtin.include_tasks:
    file: 'repalce_node.yml'
  # when: 'quorum_status | float > 0 and quorum_status | float < half_hosts | float'
  when: 'quorum_status | int  > 1  and quorum_status | int < hosts_count | int'

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
