# code: language=ansible

  - name: removwe etcd data dir if exist
    ansible.builtin.file:
      path: "{{ etcd_data_dir }}"
      state: absent

  - name: Start etcd
    ansible.builtin.systemd_service:
      name: etcd
      state: started
    tags: etcd
