Vagrant.configure(2) do |config|

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/playbook.yml"
   end

   config.vm.define "DynamicWeb" do |vmconfig|
    vmconfig.vm.box = 'ubuntu/jammy64'
    vmconfig.vm.hostname = 'DynamicWeb'

    vmconfig.vm.network "forwarded_port", guest: 8083, host: 8083
    vmconfig.vm.provider "virtualbox" do |vbx|
     vbx.memory = "2048"
     vbx.cpus = "2"
     vbx.customize ["modifyvm", :id, '--audio', 'none']
    end
   end

end
