# code: language=ansible
---
# tasks file for frontend

- name: Angie | install server | apt
  ansible.builtin.include_tasks:
    file: 'install_angie.yml'

- name: Angie | configure ssl | ssl
  ansible.builtin.include_tasks:
    file: 'configure_ssl.yml'

- name: Set cidr fact
  ansible.builtin.set_fact:
    cidr: "{{ cidr | default([]) +
              [(item.network ~ '/' ~ item.netmask) | ansible.utils.ipaddr('network/prefix')] }}"
  loop: "{{ ansible_interfaces |
              map('extract', ansible_facts, 'ipv4') |
              select('defined') | list }}"

- name: Set nginx_allwed_net fact
  ansible.builtin.set_fact:
    nginx_allowed_net: "{{ subnet }}"
  when: listen_ip | ipaddr(subnet)
  loop: "{{ cidr }}"
  loop_control:
    loop_var: subnet

- name: Angie | Configure server | cfg
  ansible.builtin.template:
    src: default.conf.j2
    dest: "/etc/angie/http.d/default.conf"
    owner: root
    group: root
    mode: '0600'
  notify: Restart Angie

