# code: language=ansible
---
- name: Set up vlan2
  ansible.builtin.template:
    src: 50-cloud-init.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml
    owner: root
    group: root
    mode: "0644"
  notify: Netplan apply
