  # code: language=ansible
---
  - name: Set up ifcfg-bond0
    template:
      src: ifcfg-bond0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0
      owner: root
      group: root
      mode: "0644"

  - name: Set up eth1,eth2
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/sysconfig/network-scripts/
      owner: root
      group: root
      mode: "0644"
    with_items:
      - ifcfg-eth1
      - ifcfg-eth2
    notify: Restart hosts
